{% set name = "pyright" %}
{% set version = "1.1.396" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyright-{{ version }}.tar.gz
  sha256: 142901f5908f5a0895be3d3befcc18bedcdb8cc1798deecaec86ef7233a29b03

build:
  number: 0
  entry_points:
    - pyright=pyright.cli:entrypoint
    - pyright-python=pyright.cli:entrypoint
    - pyright-langserver=pyright.langserver:entrypoint
    - pyright-python-langserver=pyright.langserver:entrypoint
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - nodeenv >=1.6.0
    - nodejs
    - python
    - typing_extensions >=4.1

test:
  imports:
    - pyright
  commands:
    - pip check
    - pyright --help
    - pyright-python --help
    - pyright-langserver --node-ipc
    - pyright-python-langserver --node-ipc
  requires:
    - pip

about:
  home: https://github.com/RobertCraigie/pyright-python
  summary: Command line wrapper for pyright, a static type checker
  dev_url: https://github.com/RobertCraigie/pyright-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
